AUTO_ATTACH=1
PROFILE=sway
SWAY_THEME=dark
MESA_MODE=turnip
DISPLAY_MODE=auto
MODE_POLICY=preferred
OUTPUT_MODIFIER_POLICY=ubwc
DIRECT_SCANOUT=auto
ALLOW_XWAYLAND=0
SHARE_TOUCH=0
USB_INPUT_MODE=linux-exclusive
VIDEO_ACCELERATION=auto
RESTORE_ANDROID=1
ROOTFS=/data/local/debian
SESSION_SECONDS=0
